### ISSUE TITLE
make AbstractWaitingCondition public?

### ISSUE THREAD

**Issue by alxyang** [conversant/disruptor#10]
Hey, I'd like to leverage AbstractWaitingCondition directly in my codebase.  I notice that AbstractSpinningCondition is public, but AbstractWaitingCondition is not.  

Looking through the source for AbstractWaitingCondition I don't see any specific reason to not make it public.  Can we make it publicly accessible?  Happy to open a PR to do this if needed.

If I just want the wait/signal functionality, are there better alternatives?  I searched a bit and couldn't find any literature online about other condition implementations that make use of progressive yield. 

If it's not public by design, I understand and the issue may be closed.

**Comment by jac18281828** [comment]
I don't see any problem with that.   For encapsulation reasons, I generally make things protected until needed otherwise.   There are other competing implementations but nothing packaged up as such.

Go ahead and create a PR!

**Comment by alxyang** [comment]
sounds good 👍

**Comment by jac18281828** [comment]
👍😀☕️

**Comment by alxyang** [comment]
how much work would it be to cut a release for this and get it on maven central?  it would make life easier for me if possible :)

**Comment by jac18281828** [comment]
Your wish is my command sir!   😺   I'll get to it shortly - I don't have access to my signing key right at the moment.

**Comment by jac18281828** [comment]
This has been released.
