### ISSUE TITLE
Declare an Automatic Module Name

### ISSUE THREAD

**Issue by rgoers** [conversant/disruptor#15]
Log4j 2 uses this library as an optional dependency.  One of the goals of Log4j 2 3.x is to support the Java Platform Module System. To do that every dependency it uses must declare its module name. The fully compliant way to do that would be to create a module-info.java file, but at the very least the Automatic-Module-Name header needs to be added to META-INF/MANIFEST.MF to declare the name of the module. Otherwise Java will use the jar name minus the version, which is almost always going to be a problem.

**Comment by jac18281828** [comment]
@evanwht1 you were correct.   We need to be using exports.   Will fix!

**Comment by jac18281828** [comment]
fixed in https://github.com/conversant/disruptor/releases/tag/1.2.17

@rgoers you should be good to go as soon as it propagates.
