### ISSUE TITLE
Disruptor-proxy for ActiveObjects

### ISSUE THREAD

**Issue by sirinath** [conversant/disruptor#18]
Can an equivalent of [disruptor-proxy](https://github.com/LMAX-Exchange/disruptor-proxy) be added? Ideally much faster if possible.

**Comment by jac18281828** [comment]
Sounds like an interesting challenge.   On a side note, Conversant Disruptor is already using a BlockingQueue so it should be very easy to plug into your project or business logic.  Try the MultithreadConcurrentQueue.

**Comment by sirinath** [comment]
I mean can this functionality also be added to this project so any code using disruptor-proxy can be migrated to conversant-disruptor easily.
