### ISSUE TITLE
slf4j dependency is only required by a Test : change scope to test in pom.xml

### ISSUE THREAD

**Issue by fgdrf** [conversant/disruptor#21]
https://github.com/conversant/disruptor/blob/7f3c0331ce010cbbc29df2791c57024896bede28/pom.xml#L235

I had a look from GeoTools project perspective an was wondering why slf4j is in dependency but not referenced in any runtime class.

This leads to dependency conflicts in downstream projects and could easily fixed be adding scope test

**Comment by jac18281828** [comment]
Thanks for noticing this!
