### ISSUE TITLE
Link to Disruptor-1.0.pdf is wrong

### ISSUE THREAD

**Issue by hawicz** [conversant/disruptor#9]
[The link](https://github.com/conversant/disruptor/blob/master/src/main/java/com/conversantmedia/util/concurrent/DisruptorBlockingQueue.java#L34) to the Disruptor technical paper is broken.

Can you please change it to 
http://lmax-exchange.github.io/disruptor/files/Disruptor-1.0.pdf
or
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/disruptor/Disruptor-1.0.pdf
or perhaps save a copy of the doc in this repo?

**Comment by jac18281828** [comment]
I'll just remove the outdated link.   Document is very old at this point anyway.
